<#-- $This file is distributed under the terms of the license in /doc/license.txt$ -->

<#import "listMacros.ftl" as l>

<div id="cu-identity"> <!--  generated by vivo/productMods/themes/vivo/templates/page/partials/identity.ftl -->
    <div id="cu-logo">
        <a id="insignia-link" class="clean" href="http://www.cornell.edu/" title="Cornell University"><img src="${siteIconPath}/layout/cu_logo.gif" alt="Cornell University" width="283" height="76" border="0" /></a> 
        <div id="unit-signature-links"><a id="cornell-link" class="clean" href="http://www.cornell.edu/" title="Cornell University">Cornell University</a> <a id="unit-link" class="clean" href="http://library.cornell.edu" title="Cornell University Library">Cornell University Library</a> </div>
    </div> <!-- cu-logo -->
    <div id="search-form"> 
        <form action="${urls.search}" method="get" name="gs">         
            <input type="hidden" name="home" value="${portalId}" />
            <input type="hidden" name="appname" value="${tagline!}" />
            <div id="search-input"> 
                <label for="search-form-query">SEARCH:</label>
            <#if showFlag1SearchField??>
                <select id="search-form-modifier" name="flag1" class="form-item" >
                    <option value="nofiltering" selected="selected">entire database (${loginName})</option>
                    <option value="${portalId}">${tagline!}</option>
                </select>
            <#else>
                <input type="hidden" name="flag1" value="${portalId}" />
            </#if>
                <input type="text" id="search-form-query" name="querytext" value="${querytext!}" size="20" />
                <input type="submit" id="search-form-submit" name="submit" value="go" />
            </div>
            <div id="search-filters"> 
                <input type="radio" id="search-filters1" name="sitesearch" value="vivo.cornell.edu" checked="checked" />
                <label for="search-filters1">VIVO</label>
                <input type="radio" id="search-filters2" name="sitesearch" value="www.cornell.edu" />
                <label for="search-filters2" class="force-right">Cornell</label>
            </div>
        </form>
    </div> <!-- search-form -->
</div> <!-- cu-identity -->