# SPARQL query to detect if an individual is a member of CALS
# The variable ?individualURI will be replaced by the individual's
# URI before the is query is run.
# The variable ?cause will be the value that is used as the token to 
# indicate why the individual was blacklisted and select a web page
# explaining the reason for blacklisting.
# see NetIdIdentifierFactory.java for the code that runs this query
# and clones/modifications/edit/login.jsp for the code that selects
# a page to return when a blacklisted self-editor attempts to log in.

# "AG" is the human resources code for CALS
# vivo:individual1 is Mann library


PREFIX vivo:     <http://vivo.library.cornell.edu/ns/0.1#>
PREFIX hrdata: <http://vivo.cornell.edu/ns/hr/0.9/hr.owl#>

SELECT ?cause
WHERE {
     ?individualURI  hrdata:primaryUnitCode   ?cause
     optional { 
        ?individualURI ?someJobAtMann vivo:individual1 .
        filter( ?someJobAtMann = <http://vivo.cornell.edu/ns/mannadditions/0.1#CornellLibrarianForOrganizedEndeavor> )   
      }
      optional { 
        ?individualURI ?someJobAtMann vivo:individual1 .
        filter( ?someJobAtMann =  vivo:Non-AcademicEmployeeOtherParticipantInOrganizedEndeavor)   
      }
      optional { 
        ?individualURI ?someJobAtMann vivo:individual1 .
        filter( ?someJobAtMann =  vivo:personLeadParticipantForCornellOrganizedEndeavor )   
      }      
     filter( STR(?cause) = "AG" && !bound(?someJobAtMann) )
}
limit 1
