# sparql query to detect if an individual is a member of CALS
# The variable ?individualURI will be replaced by the individual's
# URI before the is query is run.
# The variable ?cause will be the value that is used as the token to 
# indicate why the individaul was blacklisted and select a web page
# explaning the reason for blacklisting.
# see NetIdIdentifierFactory.java for the code that runs this query
# and clones/modifications/edit/login.jsp for the code that selects
# a page to return when a blacklisted self-editor attempts to log in.

# vivo:individual251 is the College of Human Ecology

PREFIX vivo:  <http://vivo.library.cornell.edu/ns/0.1#>

SELECT ?cause
WHERE {
  { ?individualURI vivo:holdFacultyAppointmentIn _:dept .
    _:dept vivo:departmentOrDivisionWithin ?cause . }
 UNION 
  { ?individualURI vivo:holdFacultyAppointmentIn ?cause }
 filter( ?cause = vivo:individual251 )
}
limit 1
