{ "ditems":[
{"type":"ditem","name":"Shuler, Michael Louis","url":"http://dev.scholars.cornell.edu/scholars/display/mls50","ditem":0,"links":["Materials Science","Microbiology","Food Science & Technology","Optics","Science & Technology - Other Topics","Environmental Sciences & Ecology","Telecommunications","Biophysics","Neurosciences & Neurology","Biotechnology & Applied Microbiology","Physics","Cell Biology","Research & Experimental Medicine","Biochemistry & Molecular Biology","Engineering","Chemistry","Surgery","Nutrition & Dietetics","Pharmacology & Pharmacy","Plant Sciences"]},
{"type":"ditem","name":"Doerschuk, Peter C.","url":"http://dev.scholars.cornell.edu/scholars/display/pd83","ditem":1,"links":["Biochemistry & Molecular Biology","Engineering","Hematology","Cardiovascular System & Cardiology","Microscopy","Endocrinology & Metabolism","Optics","Physiology","Neurosciences & Neurology","Biophysics","Cell Biology"]},
{"type":"ditem","name":"King, Michael R.","url":"http://dev.scholars.cornell.edu/scholars/display/mrk93","ditem":2,"links":["Health Care Sciences & Services","Oncology","Robotics","Mathematical & Computational Biology","Research & Experimental Medicine","Biochemistry & Molecular Biology","Engineering","Immunology","Cardiovascular System & Cardiology","Computer Science","Pharmacology & Pharmacy","Physiology","Materials Science","Hematology","Instruments & Instrumentation","Medical Laboratory Technology","Science & Technology - Other Topics","Life Sciences & Biomedicine - Other Topics","Biophysics","Genetics & Heredity","Biotechnology & Applied Microbiology","Physics","Cell Biology","Pathology","Chemistry","Electrochemistry","Infectious Diseases"]},
{"type":"ditem","name":"Bonassar, Lawrence J.","url":"http://dev.scholars.cornell.edu/scholars/display/lb244","ditem":3,"links":["Spectroscopy","Materials Science","Rheumatology","Science & Technology - Other Topics","Education & Educational Research","Biophysics","Neurosciences & Neurology","Nuclear Medicine & Medical Imaging","Biotechnology & Applied Microbiology","Polymer Science","Cell Biology","Research & Experimental Medicine","Engineering","Veterinary Sciences","Biochemistry & Molecular Biology","Chemistry","Orthopedics","Surgery","Radiology","Endocrinology & Metabolism"]},
{"type":"ditem","name":"Zipfell, Warren R.","url":"http://dev.scholars.cornell.edu/scholars/display/wrz2","ditem":4,"links":["Materials Science","Medical Laboratory Technology","Optics","Oncology","Science & Technology - Other Topics","Genetics & Heredity","Biophysics","Neurosciences & Neurology","Nuclear Medicine & Medical Imaging","Biotechnology & Applied Microbiology","Crystallography","Urology & Nephrology","Cell Biology","Research & Experimental Medicine","Gastroenterology & Hepatology","Biochemistry & Molecular Biology","Pathology","Chemistry","Microscopy","Orthopedics","Anatomy & Morphology","Radiology","Developmental Biology"]},
{"type":"ditem","name":"Spector, Jason A.","url":"http://dev.scholars.cornell.edu/scholars/display/jas456","ditem":5,"links":["Engineering","Materials Science","Chemistry","Cardiovascular System & Cardiology","Surgery","Instruments & Instrumentation","Electrochemistry","Science & Technology - Other Topics","Biotechnology & Applied Microbiology","Polymer Science","Physics","Cell Biology"]},
{"type":"ditem","name":"Schaffer, Chris B.","url":"http://dev.scholars.cornell.edu/scholars/display/cs385","ditem":6,"links":["Materials Science","Hematology","Optics","Science & Technology - Other Topics","Neurosciences & Neurology","Biophysics","Physics","Cell Biology","Research & Experimental Medicine","Engineering","Chemistry","Cardiovascular System & Cardiology","Surgery","Pharmacology & Pharmacy","Endocrinology & Metabolism","Physiology"]},
{"type":"ditem","name":"Williams, Rebecca M.","url":"http://dev.scholars.cornell.edu/scholars/display/rw36","ditem":7,"links":["Materials Science","Rheumatology","Optics","Oncology","Science & Technology - Other Topics","Biophysics","Neurosciences & Neurology","Nuclear Medicine & Medical Imaging","Biotechnology & Applied Microbiology","Cell Biology","Research & Experimental Medicine","Biochemistry & Molecular Biology","Engineering","Microscopy","Orthopedics","Radiology","Physiology","Developmental Biology"]},
{"type":"ditem","name":"Putnam, David","url":"http://dev.scholars.cornell.edu/scholars/display/dap43","ditem":8,"links":["Biochemistry & Molecular Biology","Engineering","Materials Science","Immunology","Pharmacology & Pharmacy","Science & Technology - Other Topics","Biotechnology & Applied Microbiology","Research & Experimental Medicine"]},
{"type":"ditem","name":"Reinhart-King, Cynthia A.","url":"http://dev.scholars.cornell.edu/scholars/display/cak57","ditem":9,"links":["Materials Science","Hematology","Oncology","Science & Technology - Other Topics","Biophysics","Polymer Science","Physics","Cell Biology","Mathematical & Computational Biology","Research & Experimental Medicine","Biochemistry & Molecular Biology","Engineering","Chemistry","Cardiovascular System & Cardiology","Pharmacology & Pharmacy","Physiology","Developmental Biology"]},
{"type":"ditem","name":"Wang, Yi","url":"http://dev.scholars.cornell.edu/scholars/display/yw233","ditem":10,"links":["Spectroscopy","Geology","Science & Technology - Other Topics","Biophysics","Neurosciences & Neurology","Nuclear Medicine & Medical Imaging","Biotechnology & Applied Microbiology","Research & Experimental Medicine","Biochemistry & Molecular Biology","Engineering","Toxicology","Cardiovascular System & Cardiology","Computer Science","Radiology","Plant Sciences","Imaging Science & Photographic Technology"]},
{"type":"ditem","name":"Pannullo, Susan C.","url":"http://dev.scholars.cornell.edu/scholars/display/sbc76","ditem":11,"links":["Surgery","Food Science & Technology","Neurosciences & Neurology","Biotechnology & Applied Microbiology"]},
{"type":"ditem","name":"Seo, Bo Ri","url":"http://dev.scholars.cornell.edu/scholars/display/bs438","ditem":12,"links":["Engineering","Materials Science","Pharmacology & Pharmacy","Science & Technology - Other Topics","Biophysics","Cell Biology","Research & Experimental Medicine"]},
{"type":"ditem","name":"Fischbach, Claudia","url":"http://dev.scholars.cornell.edu/scholars/display/cf99","ditem":13,"links":["Biochemistry & Molecular Biology","Engineering","Materials Science","Chemistry","Pharmacology & Pharmacy","Science & Technology - Other Topics","Endocrinology & Metabolism","Biophysics","Biotechnology & Applied Microbiology","Crystallography","Cell Biology","Research & Experimental Medicine"]},
{"type":"ditem","name":"Archer, Shivaun D.","url":"http://dev.scholars.cornell.edu/scholars/display/sda4","ditem":14,"links":["Materials Science","Chemistry","Science & Technology - Other Topics","Education & Educational Research","Life Sciences & Biomedicine - Other Topics"]},
{"type":"ditem","name":"Olbricht, William L.","url":"http://dev.scholars.cornell.edu/scholars/display/wlo1","ditem":15,"links":["Hematology","Instruments & Instrumentation","Science & Technology - Other Topics","Life Sciences & Biomedicine - Other Topics","Biophysics","Neurosciences & Neurology","Nuclear Medicine & Medical Imaging","Physics","Mathematical & Computational Biology","Engineering","Chemistry","Cardiovascular System & Cardiology","Surgery","Pharmacology & Pharmacy","Electrochemistry","Radiology","Endocrinology & Metabolism","Physiology"]},
{"type":"ditem","name":"van der Meulen, Marjolein C. H.","url":"http://dev.scholars.cornell.edu/scholars/display/mcv3","ditem":16,"links":["Materials Science","Rheumatology","Science & Technology - Other Topics","Life Sciences & Biomedicine - Other Topics","Biophysics","Biotechnology & Applied Microbiology","Cell Biology","Biochemistry & Molecular Biology","Engineering","Veterinary Sciences","Sport Sciences","Surgery","Orthopedics","Endocrinology & Metabolism","Physiology"]},
{"type":"ditem","name":"Cosgrove, Benjamin D.","url":"http://dev.scholars.cornell.edu/scholars/display/bdc68","ditem":17,"links":["Biochemistry & Molecular Biology","Cell Biology","Research & Experimental Medicine"]},
{"type":"ditem","name":"Schafer, Andrew I.","url":"http://dev.scholars.cornell.edu/scholars/display/ais63","ditem":18,"links":["Cardiovascular System & Cardiology","Hematology","Endocrinology & Metabolism","Physiology","Neurosciences & Neurology"]},
{"type":"ditem","name":"Esch, Mandy Brigitte","url":"http://dev.scholars.cornell.edu/scholars/display/mbe2","ditem":19,"links":["Engineering","Biochemistry & Molecular Biology","Materials Science","Chemistry","Pharmacology & Pharmacy","Science & Technology - Other Topics","Biotechnology & Applied Microbiology","Cell Biology","Research & Experimental Medicine"]},
{"type":"ditem","name":"Lammerding, Jan","url":"http://dev.scholars.cornell.edu/scholars/display/jl2792","ditem":20,"links":["Biochemistry & Molecular Biology","Science & Technology - Other Topics","Genetics & Heredity","Biophysics","Cell Biology"]},
{"type":"ditem","name":"Nishimura, Nozomi","url":"http://dev.scholars.cornell.edu/scholars/display/nn62","ditem":21,"links":["Hematology","Optics","Science & Technology - Other Topics","Neurosciences & Neurology","Biophysics","Biotechnology & Applied Microbiology","Cell Biology","Research & Experimental Medicine","Engineering","Cardiovascular System & Cardiology","Surgery","Endocrinology & Metabolism","Physiology"]},
{"type":"ditem","name":"Hernandez, Christopher J.","url":"http://dev.scholars.cornell.edu/scholars/display/cjh275","ditem":22,"links":["Engineering","Biochemistry & Molecular Biology","Chemistry","Surgery","Orthopedics","Endocrinology & Metabolism","Science & Technology - Other Topics","Biophysics"]},
{"type":"ditem","name":"Butcher, Jonathan T.","url":"http://dev.scholars.cornell.edu/scholars/display/jtb47","ditem":23,"links":["Materials Science","Hematology","Education & Educational Research","Life Sciences & Biomedicine - Other Topics","Biophysics","Biotechnology & Applied Microbiology","Physics","Cell Biology","Research & Experimental Medicine","Engineering","Biochemistry & Molecular Biology","Veterinary Sciences","Cardiovascular System & Cardiology","Anatomy & Morphology","Pharmacology & Pharmacy","Mechanics","Physiology","Developmental Biology","Reproductive Biology"]},
],
"themes":[
{"type":"theme","name":"Anatomy & Morphology","description":"","slug":"Anatomy & Morphology"},
{"type":"theme","name":"Biochemistry & Molecular Biology","description":"","slug":"Biochemistry & Molecular Biology"},
{"type":"theme","name":"Biophysics","description":"","slug":"Biophysics"},
{"type":"theme","name":"Biotechnology & Applied Microbiology","description":"","slug":"Biotechnology & Applied Microbiology"},
{"type":"theme","name":"Cardiovascular System & Cardiology","description":"","slug":"Cardiovascular System & Cardiology"},
{"type":"theme","name":"Cell Biology","description":"","slug":"Cell Biology"},
{"type":"theme","name":"Chemistry","description":"","slug":"Chemistry"},
{"type":"theme","name":"Computer Science","description":"","slug":"Computer Science"},
{"type":"theme","name":"Crystallography","description":"","slug":"Crystallography"},
{"type":"theme","name":"Developmental Biology","description":"","slug":"Developmental Biology"},
{"type":"theme","name":"Education & Educational Research","description":"","slug":"Education & Educational Research"},
{"type":"theme","name":"Electrochemistry","description":"","slug":"Electrochemistry"},
{"type":"theme","name":"Endocrinology & Metabolism","description":"","slug":"Endocrinology & Metabolism"},
{"type":"theme","name":"Engineering","description":"","slug":"Engineering"},
{"type":"theme","name":"Environmental Sciences & Ecology","description":"","slug":"Environmental Sciences & Ecology"},
{"type":"theme","name":"Food Science & Technology","description":"","slug":"Food Science & Technology"},
{"type":"theme","name":"Gastroenterology & Hepatology","description":"","slug":"Gastroenterology & Hepatology"},
{"type":"theme","name":"Genetics & Heredity","description":"","slug":"Genetics & Heredity"},
{"type":"theme","name":"Geology","description":"","slug":"Geology"},
{"type":"theme","name":"Health Care Sciences & Services","description":"","slug":"Health Care Sciences & Services"},
{"type":"theme","name":"Hematology","description":"","slug":"Hematology"},
{"type":"theme","name":"Imaging Science & Photographic Technology","description":"","slug":"Imaging Science & Photographic Technology"},
{"type":"theme","name":"Immunology","description":"","slug":"Immunology"},
{"type":"theme","name":"Infectious Diseases","description":"","slug":"Infectious Diseases"},
{"type":"theme","name":"Instruments & Instrumentation","description":"","slug":"Instruments & Instrumentation"},
{"type":"theme","name":"Life Sciences & Biomedicine - Other Topics","description":"","slug":"Life Sciences & Biomedicine - Other Topics"},
{"type":"theme","name":"Materials Science","description":"","slug":"Materials Science"},
{"type":"theme","name":"Mathematical & Computational Biology","description":"","slug":"Mathematical & Computational Biology"},
{"type":"theme","name":"Mechanics","description":"","slug":"Mechanics"},
{"type":"theme","name":"Medical Laboratory Technology","description":"","slug":"Medical Laboratory Technology"},
{"type":"theme","name":"Microbiology","description":"","slug":"Microbiology"},
{"type":"theme","name":"Microscopy","description":"","slug":"Microscopy"},
{"type":"theme","name":"Neurosciences & Neurology","description":"","slug":"Neurosciences & Neurology"},
{"type":"theme","name":"Nuclear Medicine & Medical Imaging","description":"","slug":"Nuclear Medicine & Medical Imaging"},
{"type":"theme","name":"Nutrition & Dietetics","description":"","slug":"Nutrition & Dietetics"},
{"type":"theme","name":"Oncology","description":"","slug":"Oncology"},
{"type":"theme","name":"Optics","description":"","slug":"Optics"},
{"type":"theme","name":"Orthopedics","description":"","slug":"Orthopedics"},
{"type":"theme","name":"Pathology","description":"","slug":"Pathology"},
{"type":"theme","name":"Pharmacology & Pharmacy","description":"","slug":"Pharmacology & Pharmacy"},
{"type":"theme","name":"Physics","description":"","slug":"Physics"},
{"type":"theme","name":"Physiology","description":"","slug":"Physiology"},
{"type":"theme","name":"Plant Sciences","description":"","slug":"Plant Sciences"},
{"type":"theme","name":"Polymer Science","description":"","slug":"Polymer Science"},
{"type":"theme","name":"Radiology","description":"","slug":"Radiology"},
{"type":"theme","name":"Reproductive Biology","description":"","slug":"Reproductive Biology"},
{"type":"theme","name":"Research & Experimental Medicine","description":"","slug":"Research & Experimental Medicine"},
{"type":"theme","name":"Rheumatology","description":"","slug":"Rheumatology"},
{"type":"theme","name":"Robotics","description":"","slug":"Robotics"},
{"type":"theme","name":"Science & Technology - Other Topics","description":"","slug":"Science & Technology - Other Topics"},
{"type":"theme","name":"Spectroscopy","description":"","slug":"Spectroscopy"},
{"type":"theme","name":"Sport Sciences","description":"","slug":"Sport Sciences"},
{"type":"theme","name":"Surgery","description":"","slug":"Surgery"},
{"type":"theme","name":"Telecommunications","description":"","slug":"Telecommunications"},
{"type":"theme","name":"Toxicology","description":"","slug":"Toxicology"},
{"type":"theme","name":"Urology & Nephrology","description":"","slug":"Urology & Nephrology"},
{"type":"theme","name":"Veterinary Sciences","description":"","slug":"Veterinary Sciences"},
]};