<#-- $This file is distributed under the terms of the license in /doc/license.txt$ -->

<#-- List individuals in the requested class. -->

<#import "lib-list.ftl" as l>

<#include "individualList-checkForData.ftl">

${stylesheets.add('<link rel="stylesheet" href="${urls.base}/css/browseIndex.css" />')}
<div class="row scholars-row">
	<div id="index-container" class="col-sm-12 scholars-container">
	<section class="individualListx">
	    <h2 class="searchResultsHeader">${title!}
	        <#if rdfUrl?has_content>
	            <span class="rdfLink"><a class="icon-rdf" href="${rdfUrl}" title="${i18n().view_list_in_rdf(title)}">${i18n().rdf}</a></span>
	        </#if>
	    </h2>
	    <#if subtitle?has_content>
	        <h4>${subtitle}</h4>
	    </#if>
	    <#if (!noData)>
	        <#if errorMessage?has_content>
	            <p>${errorMessage}</p>
	        <#else>
	            <#assign pagination>
	                <#if (pages?has_content && pages?size > 1)>
	                    <div class="panel-heading" style="width:100%;background-color:#394e6b;padding:10px 0 10px 0;border-color:#394e6b">
	                    <ul class="paginationx">
							<li style="float:left;font-size:14px;color:#fff;margin:0 10px 20px 10px;">pages:</li>
	                        <#list pages as page>
	                            <#if page.selected>
	                                <li class="active-browse-links" style="display:inline;font-size:14px;padding-right:20px;">${page.text}</li>
	                            <#else>
	                                <#-- RY Ideally the urls would be generated by the controller; see search-pagedResults.ftl -->
	                                <li style="color:#fff;display:inline;font-size:14px;padding-right:20px;">
										<a class="browse-links" href="${urls.base}/individuallist?${page.param}&vclassId=${vclassId?url}" title="page text">${page.text}</a>
									</li>
	                            </#if>
	                        </#list>
	                    </ul>
						</div>
	                </#if>
	            </#assign>
	            <div id="results-container" class="panel panel-default" style="clear:both;margin-left:12px;">
					
	            		${pagination}
	            
	            	<ul class="searchhits">
	                	<#list individuals as individual>
	                    	<li>       
	                        	<@shortView uri=individual.uri viewContext="index" />
	                    	</li>
	                	</#list>
	            	</ul>
				</div>
				<#if (pages?has_content && pages?size > 1)>
	            	<div id="results-container" class="panel panel-default" style="margin-left:10px;padding-bottom:1px;background-color:#394e6b;">
	            		${pagination}
					</div>
				</#if>
	        </#if>
	    <#else>
	        ${noDataNotification}
	    </#if>
	</section> <!-- .individualList -->
  </dev>
</dev>