# SPARQL query to detect if an individual is a member of CALS
# The variable ?individualURI will be replaced by the individual's
# URI before the is query is run.
# The variable ?cause will be the value that is used as the token to 
# indicate why the individual was blacklisted and select a web page
# explaining the reason for blacklisting.
# see SelfEditingIdentifierFactory.java for the code that runs this query
# and clones/modifications/edit/login.jsp for the code that selects
# a page to return when a blacklisted self-editor attempts to log in.

# "AG" is the human resources code for CALS
# vivo:individual1 is Mann library


PREFIX vivo:   <http://vivo.cornell.edu/individual/>
PREFIX hrdata: <http://vivo.cornell.edu/ns/hr/0.9/hr.owl#>
PREFIX core:   <http://vivoweb.org/ontology/core#>

SELECT ?cause
WHERE {
     ?individualURI hrdata:primaryUnitCode   ?cause
     optional {
         ?individualURI core:personInPosition ?someJobAtMann .
         ?someJobAtMann core:positionInOrganization vivo:individual1
     }
     filter( STR(?cause) = "AG" && !bound(?someJobAtMann) )
}
limit 1
