PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo:  <http://vivo.library.cornell.edu/ns/0.1#>
PREFIX mann:  <http://vivo.cornell.edu/ns/mannadditions/0.1#>

CONSTRUCT {
    ?course rdf:type ?type .
    ?course vitro:moniker ?moniker .
    ?course rdfs:label ?label .
    ?course vitro:modTime ?modTime .
    ?course <http://vitro.mannlib.cornell.edu/ns/cornell/stars/classes#class_FacilityLdescr> ?facililty .
    ?course <http://vitro.mannlib.cornell.edu/ns/cornell/stars/classes#class_AcademicTermSdescr> "2009FA" .
    ?course <http://vitro.mannlib.cornell.edu/ns/cornell/stars/classes#class_CourseIDandClassNbr> ?courseId .
    ?course ?p ?o .
    ?oo ?pp ?course .
} WHERE {
    ?course rdf:type vivo:SemesterClass .
    ?course rdf:type ?type .
    ?course vitro:moniker ?moniker .
    ?course rdfs:label ?label .
   OPTIONAL {
        ?course vitro:modTime ?modTime .
    }
    OPTIONAL {
        ?course <http://vitro.mannlib.cornell.edu/ns/cornell/stars/classes#class_FacilityLdescr> ?facililty .
    }
    ?course <http://vitro.mannlib.cornell.edu/ns/cornell/stars/classes#class_AcademicTermSdescr> "2009FA" .
    ?course <http://vitro.mannlib.cornell.edu/ns/cornell/stars/classes#class_CourseIDandClassNbr> ?courseId .
    ?course ?p ?o 
    FILTER(regex(str(?p),"^http://vivo.library.cornell.edu/ns/0.1#"))
    ?oo ?pp ?course 
}
